export { WelcomePage } from './home/welcome-page';
export { About as HomeAbout } from './home/about';
export { Course as HomeCourse } from './home/course';
export { Events as HomeEvents } from './home/events';
export { Blog as HomeBlog } from './home/blog';
export { Newsletter } from './home/newsletter';
export { Experience } from './home/experience';
export { About } from './about';
export { Course } from './course';
export { Exams } from './exams';
export { Pricelist } from './pricelist';
export { Blog, BlogPage } from './blog';
